# Generated by Django 4.2.1 on 2023-06-02 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=180)),
                ('description', models.TextField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=180)),
                ('description', models.TextField(max_length=180)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pg_name', models.CharField(blank=True, max_length=180)),
                ('total_beds', models.IntegerField()),
                ('pg_for', models.CharField(choices=[('girls', 'Girls'), ('boys', 'Boys'), ('coliving', 'Co-living')], max_length=20)),
                ('best_suited_for', models.CharField(choices=[('students', 'Students'), ('professionals', 'Professionals')], max_length=20)),
                ('meals_available', models.BooleanField()),
                ('notice_period', models.IntegerField()),
                ('lock_in_period', models.IntegerField()),
                ('common_areas', models.CharField(choices=[('living_room', 'Living Room'), ('kitchen', 'Kitchen'), ('dining_hall', 'Dining Hall'), ('study_room', 'Study Room'), ('breakout_areas', 'Breakout Areas')], max_length=20)),
                ('property_managed_by', models.CharField(choices=[('landlord', 'Landlord'), ('caretaker', 'Caretaker'), ('dedicated_professional', 'Dedicated Professional')], max_length=30)),
                ('property_manager_stays_at_property', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgs.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgs.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='products', to='pgs.productimage'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=180)),
                ('customer_email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgs.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
