# Generated by Django 4.2.1 on 2023-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
