# Generated by Django 4.2.1 on 2023-06-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best_suited_for',
        ),
        migrations.RemoveField(
            model_name='product',
            name='common_areas',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lock_in_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meals_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pg_for',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pg_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='property_managed_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='property_manager_stays_at_property',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_beds',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to='products/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
