# Generated by Django 4.2.1 on 2023-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0004_remove_product_best_suited_for_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='best_suited_for',
            field=models.CharField(choices=[('students', 'Students'), ('professionals', 'Professionals')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='lock_in_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='meals_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='notice_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pg_for',
            field=models.CharField(choices=[('girls', 'Girls'), ('boys', 'Boys'), ('coliving', 'Co-living')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='pg_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='property_managed_by',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('caretaker', 'Caretaker'), ('dedicated_professional', 'Dedicated Professional')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='property_manager_stays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='total_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='common_areas',
            field=models.ManyToManyField(related_name='products', to='pgs.commonarea'),
        ),
    ]
