# Generated by Django 4.2.1 on 2023-06-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0005_commonarea_product_best_suited_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='common_areas',
        ),
        migrations.AddField(
            model_name='product',
            name='common_areas',
            field=models.CharField(blank=True, choices=[('living_room', 'Living Room'), ('kitchen', 'Kitchen'), ('dining_hall', 'Dining Hall'), ('study_room', 'Study Room'), ('breakout_areas', 'Breakout Areas')], max_length=255, null=True),
        ),
    ]
