# Generated by Django 4.2.1 on 2023-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0006_remove_product_common_areas_product_common_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='common_areas',
        ),
        migrations.AddField(
            model_name='product',
            name='common_areas',
            field=models.ManyToManyField(related_name='products', to='pgs.commonarea'),
        ),
    ]
