# Generated by Django 4.2.1 on 2023-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0007_remove_product_common_areas_product_common_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TopAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='furnishing_in_property',
            field=models.ManyToManyField(related_name='products', to='pgs.furnishing'),
        ),
        migrations.AddField(
            model_name='product',
            name='security_amenities',
            field=models.ManyToManyField(related_name='products', to='pgs.securityamenity'),
        ),
        migrations.AddField(
            model_name='product',
            name='services_in_property',
            field=models.ManyToManyField(related_name='products', to='pgs.services'),
        ),
        migrations.AddField(
            model_name='product',
            name='topAmenities_in_property',
            field=models.ManyToManyField(related_name='products', to='pgs.topamenities'),
        ),
    ]
