# Generated by Django 4.2.1 on 2023-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0009_product_single_sharing_product_single_sharing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='Banglore', max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='double_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='double_sharing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='locality',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='security_deposite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='triple_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='triple_sharing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
