# Generated by Django 4.2.1 on 2023-06-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0014_product_more_images_additionalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='double_sharing_deposite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='single_sharing_deposite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='triple_sharing_deposite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
