# Generated by Django 4.2.1 on 2023-06-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0015_product_double_sharing_deposite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedded_map_src_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='best_suited_for',
            field=models.CharField(choices=[('students', 'Students'), ('professionals', 'Professionals'), ('students & professionals', 'students & professionals')], default='', max_length=40),
        ),
    ]
