# Generated by Django 4.2.1 on 2023-06-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0016_product_embedded_map_src_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='more_images',
        ),
    ]
