# Generated by Django 4.2.1 on 2023-06-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0019_foodimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='product',
            name='electric_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='maintaince_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
