# Generated by Django 4.2.1 on 2023-06-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0021_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pg_name',
            field=models.CharField(blank=True, default=models.CharField(max_length=180), max_length=180),
        ),
    ]
