# Generated by Django 4.2.1 on 2023-06-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0022_alter_product_pg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalimage',
            name='delete_image',
            field=models.BooleanField(default=False),
        ),
    ]
