# Generated by Django 4.2.1 on 2023-06-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0023_additionalimage_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalimage',
            name='delete_image',
        ),
    ]
