# Generated by Django 4.2.1 on 2023-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0024_remove_additionalimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.ImageField(help_text='Only up to 5 images are supported.', upload_to='more_images/'),
        ),
    ]
