# Generated by Django 4.2.1 on 2023-07-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0026_alter_foodimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='locality',
            field=models.CharField(choices=[('Marathalli', 'Marathalli'), ('BTM Layout', 'BTM Layout'), ('Electronic City', 'Electronic City'), ('Manyata Tech Park', 'Manyata Tech Park'), ('Whitefield', 'Whitefield'), ('Sarjapur Road', 'Sarjapur Road'), ('Madiwala', 'Madiwala'), ('Koramangala', 'Koramangala'), ('HSR Layout', 'HSR Layout'), ('Bellandur', 'Bellandur')], default='', max_length=25),
        ),
    ]
