# Generated by Django 4.2.1 on 2023-07-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0027_alter_product_locality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
