# Generated by Django 4.2.1 on 2023-08-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0028_delete_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'PG Category', 'verbose_name_plural': 'PG Categories'},
        ),
    ]
