# Generated by Django 4.2.1 on 2023-08-03 16:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0031_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='your_default_phone_number', max_length=128, region=None),
        ),
    ]
