# Generated by Django 4.2.1 on 2023-08-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0032_product_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pg_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='security_deposite',
        ),
    ]
