# Generated by Django 4.2.1 on 2023-08-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0033_remove_product_category_remove_product_pg_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
