# Generated by Django 4.2.1 on 2023-08-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_bannerblissad_cozycornersad_exclusiveoffersad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cozycornersad',
            name='ad_ptr',
        ),
        migrations.RemoveField(
            model_name='exclusiveoffersad',
            name='ad_ptr',
        ),
        migrations.RemoveField(
            model_name='featuredgemsad',
            name='ad_ptr',
        ),
        migrations.RemoveField(
            model_name='herospotlightad',
            name='ad_ptr',
        ),
        migrations.RemoveField(
            model_name='toppicksad',
            name='ad_ptr',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='title',
        ),
        migrations.AddField(
            model_name='ad',
            name='banner_image',
            field=models.ImageField(default=None, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='side_image',
            field=models.ImageField(default=None, upload_to='ads/'),
        ),
        migrations.DeleteModel(
            name='BannerBlissAd',
        ),
        migrations.DeleteModel(
            name='CozyCornersAd',
        ),
        migrations.DeleteModel(
            name='ExclusiveOffersAd',
        ),
        migrations.DeleteModel(
            name='FeaturedGemsAd',
        ),
        migrations.DeleteModel(
            name='HeroSpotlightAd',
        ),
        migrations.DeleteModel(
            name='TopPicksAd',
        ),
    ]
