# Generated by Django 4.2.1 on 2023-08-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='link',
        ),
    ]
