# Generated by Django 4.2.1 on 2023-08-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquelocalityads23',
            name='Bellandur_Layout',
        ),
        migrations.RemoveField(
            model_name='uniquelocalityads23',
            name='ElectronicCity_Layout',
        ),
        migrations.RemoveField(
            model_name='uniquelocalityads23',
            name='HSR_Layout',
        ),
        migrations.RemoveField(
            model_name='uniquelocalityads23',
            name='Koramangala_Layout',
        ),
        migrations.RemoveField(
            model_name='uniquelocalityads23',
            name='Madiwala_Layout',
        ),
        migrations.RemoveField(
            model_name='uniquelocalityads23',
            name='ManyataTechPark_Layout',
        ),
        migrations.RemoveField(
            model_name='uniquelocalityads23',
            name='SarjapurRoad_Layout',
        ),
        migrations.RemoveField(
            model_name='uniquelocalityads23',
            name='Whitefield_Layout',
        ),
    ]
