# Generated by Django 4.2.1 on 2023-08-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0002_remove_uniquelocalityads23_bellandur_layout_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniqueLocalityAds23',
        ),
    ]
