# Generated by Django 4.2.1 on 2023-08-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0034_delete_category'),
        ('ads_manager', '0003_delete_uniquelocalityads23'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(choices=[('Marathalli', 'Marathalli'), ('BTM Layout', 'BTM Layout'), ('Electronic City', 'Electronic City'), ('Manyata Tech Park', 'Manyata Tech Park'), ('Whitefield', 'Whitefield'), ('Sarjapur Road', 'Sarjapur Road'), ('Madiwala', 'Madiwala'), ('Koramangala', 'Koramangala'), ('HSR Layout', 'HSR Layout'), ('Bellandur', 'Bellandur')], max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_ad', to='pgs.product')),
            ],
        ),
    ]
