# Generated by Django 4.2.1 on 2023-08-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0034_delete_category'),
        ('ads_manager', '0004_premiumads'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(choices=[('Marathalli', 'Marathalli'), ('BTM Layout', 'BTM Layout'), ('Electronic City', 'Electronic City'), ('Manyata Tech Park', 'Manyata Tech Park'), ('Whitefield', 'Whitefield'), ('Sarjapur Road', 'Sarjapur Road'), ('Madiwala', 'Madiwala'), ('Koramangala', 'Koramangala'), ('HSR Layout', 'HSR Layout'), ('Bellandur', 'Bellandur')], max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, null=True, related_name='popular_ads', to='pgs.product')),
            ],
        ),
    ]
