# Generated by Django 4.2.1 on 2023-08-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0034_delete_category'),
        ('ads_manager', '0006_alter_popularads_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularads',
            name='locality',
            field=models.CharField(choices=[('Marathalli', 'Marathalli'), ('BTM Layout', 'BTM Layout'), ('Electronic City', 'Electronic City'), ('Manyata Tech Park', 'Manyata Tech Park'), ('Whitefield', 'Whitefield'), ('Sarjapur Road', 'Sarjapur Road'), ('Madiwala', 'Madiwala'), ('Koramangala', 'Koramangala'), ('HSR Layout', 'HSR Layout'), ('Bellandur', 'Bellandur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='popularads',
            name='products',
            field=models.ManyToManyField(related_name='popular_ads', to='pgs.product'),
        ),
    ]
